import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { supabase } from '../config/supabase'
import { useEffect } from 'react'
export default function Home() {
  useEffect(() => {
    const data=async ()=>{
    const {data,error}=await supabase.from("task").select()
    if(data){
      console.log(data)
    }
  }
   data()
  }, []);
 
  return (
    <div className="bg-blue-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Welcome to Index</h1>
      </div>
    
    </div>
  )
}
