import Head from 'next/head'
import { supabase } from '../config/supabase'
import { useEffect,useState } from 'react'
import TaskItem from '../components/TaskItem'
import AddTask from '../components/AddTask';
export default function Home() {
  const [taskData, setTaskData] = useState([]);
  const fetchData=async ()=>{
      const {data,error}=await supabase.from("task").select() .order('id', { ascending: false })
      if(data){
        setTaskData(data)
      }
      if(error){
        window.alert("Internet Issue for loading data")
        fetchData()
      }
    } 
  
  useEffect(() => {
    
    fetchData()
    
  }, [])
  

  return (
    <div  >
      <Head>
        <title>Task App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     
     <div className='grid h-80 place-items-center'>
     <div className={`bg-white p-3 rounded-md ${taskData.length >0 ? 'mt-28':''}`}>
        <AddTask dataCall={fetchData} />

      {
        taskData.length >0 && <TaskItem fetchData={fetchData} data={taskData}/>
      }
      </div>
     </div>
    
    </div>
  )
}
